name: Build Lambda

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build JAR
        run: mvn clean package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::050922969172:role/github-action
          aws-region: eu-west-1

      - name: Upload JAR to S3 artifact bucket
        run: |
          aws s3 cp target/lambdaapp-1.0-SNAPSHOT.jar \
          s3://harneet-artifact-bucket/lambdaapp/lambdaapp.jar